LIST P=16F84, F=INHX8M
INCLUDE<P16F84.INC>
__CONFIG _CP_OFF & _WDT_OFF & _XT_OSC

TEMP EQU 10H
COUNT EQU 11H
ORG 0000H
GOTO INIT


INIT	BSF STATUS, RP0
		CLRF TRISB
		MOVLW B'00000100' ;1:32 TMR0 Prescaler
		MOVWF OPTION_REG
		BCF STATUS, RP0
		MOVLW 00H
		MOVWF PORTB
	

MAIN	CALL DELAY
		INCF PORTB, F
		MOVLW 0AH
		XORWF PORTB, W
		BTFSS STATUS, Z
		GOTO MAIN
		CLRF PORTB
		GOTO MAIN

 DELAY	MOVLW D'122'
		MOVWF COUNT
 DELAY2	DECFSZ COUNT
		GOTO DELAY2
		RETURN

END