INCLUDE<P16F84.INC>
LIST P=16F84, F=INHX8M
__CONFIG _CP_OFF & _WDT_OFF & _XT_OSC

	ORG 0000H
	GOTO MAIN
	ORG 0004H
	GOTO INT_ROUTINE

MAIN	CLRF STATUS
		BSF STATUS, RP0
		MOVLW B'00000100'
		MOVWF OPTION_REG
		MOVLW 00H
		MOVWF TRISA
		BSF INTCON, T0IE
		BSF INTCON, GIE
		BCF STATUS, RP0
		MOVLW 00H
		MOVWF PORTB

AGAIN	NOP
		GOTO AGAIN

INT_ROUTINE
		BCF INTCON, GIE
		BTFSS INTCON, T0IF
		RETFIE
		BCF INTCON, T0IF
		COMF PORTA, F
		RETFIE

END