LIST P=16F84, F=INHX8M
INCLUDE<P16F84.INC>
__CONFIG 3FF5H

FLAG EQU 0CH
TEMP EQU 0DH
IHAP EQU 0EH
COMP EQU 0FH

ORG 0000H
GOTO INIT
ORG 0004H
GOTO INT_ROUTINE
BCF STATUS, RP0
MOVLW 00H
MOVWF COMP
MOVWF PORTB
INIT	BSF STATUS,RP0
		MOVLW 4DH
		MOVWF OPTION_REG
		MOVLW 01H
		MOVWF TRISB
		BSF INTCON, GIE
		BSF INTCON, INTE
		BCF STATUS, RP0
		BCF FLAG, 0
		
MAIN	BTFSS FLAG, 0
		GOTO MAIN
		BCF FLAG, 0
		COMF COMP, F
		BTFSS COMP, 0
		GOTO LR
		GOTO LL

LL			MOVLW 01H
			MOVWF TEMP
			MOVLW 07H
			MOVWF IHAP	
LOOPLEFT	RLF TEMP, F
			MOVFW TEMP
			MOVWF PORTB
			SLEEP
			DECFSZ IHAP, F
			GOTO LOOPLEFT
			BSF INTCON, GIE
			GOTO MAIN
			
LR			MOVLW 80H
			MOVWF TEMP
			MOVLW 06H
			MOVWF IHAP
LOOPRIGHT	RRF TEMP, F
			MOVFW TEMP
			MOVWF PORTB
			SLEEP
			DECFSZ IHAP, F
			GOTO LOOPRIGHT
			BSF INTCON, GIE
			GOTO MAIN

INT_ROUTINE
		BCF INTCON, GIE
		BTFSS INTCON, INTF
		RETFIE
		BCF INTCON, INTF
		BSF FLAG, 0
		RETFIE
END