LIST P=16F84, F=INHX8M
INCLUDE<P16F84.INC>
__CONFIG _CP_OFF & _WDT_OFF & _XT_OSC

TEMP EQU 10H
COUNT EQU 11H
ORG 0000H
GOTO INIT
ORG 0004H
GOTO INT_ROUTINE


INIT	BSF STATUS, RP0
		CLRF TRISB
		MOVLW B'00000100' ;1:32 TMR0 Prescaler
		MOVWF OPTION_REG
		BSF INTCON, GIE
		BSF INTCON, T0IE
		BCF STATUS, RP0
		MOVLW 00H
		MOVWF PORTB
		MOVLW D'1'
		MOVWF COUNT
	

MAIN	CALL DELAY
		MOVLW D'122'
		MOVWF COUNT
		INCF PORTB, F
		MOVLW 0AH
		XORWF PORTB, W
		BTFSS STATUS, Z
		GOTO MAIN
		CLRF PORTB
		GOTO MAIN

 DELAY:	NOP
 		MOVLW 00H
		XORWF COUNT, W
		BTFSS STATUS, Z
		GOTO DELAY
		RETURN


INT_ROUTINE
		BCF INTCON, T0IF
		DECF COUNT
		RETFIE
END